actuator_pid_controller:
  ros__parameters:
    type: pid_command_controller/ActuatorPIDCommandController
    actuator_names:
      - gripper_right_finger_actuator
      - gripper_left_finger_actuator


    tuning_mode: true

    position:
      gripper_right_finger_actuator:
        proportional: 0.0003
        integral: 0.0
        derivative: 0.00000002
    velocity:
      gripper_right_finger_actuator:
        proportional: 0.2
        integral: 5.0
        derivative: 0.00003
    current:
      gripper_right_finger_actuator:
        proportional: 2.0
        integral: 2500.0
        derivative: 0.0

    position:
      gripper_left_finger_actuator:
        proportional: 0.0003
        integral: 0.0
        derivative: 0.00000002
    velocity:
      gripper_left_finger_actuator:
        proportional: 0.2
        integral: 5.0
        derivative: 0.00003
    current:
      gripper_left_finger_actuator:
        proportional: 2.0
        integral: 2500.0
        derivative: 0.0
