/**:
  ros__parameters:
    motions:
      home_teleop_arms:
        joints: [arm_teleop_left_1_joint, arm_teleop_left_2_joint, arm_teleop_left_3_joint, arm_teleop_left_4_joint, arm_teleop_left_5_joint, arm_teleop_left_6_joint, arm_teleop_left_7_joint, arm_teleop_right_1_joint, arm_teleop_right_2_joint, arm_teleop_right_3_joint, arm_teleop_right_4_joint, arm_teleop_right_5_joint, arm_teleop_right_6_joint, arm_teleop_right_7_joint]
        times_from_start: [0.0, 5.0, 10.0]
        positions: [1.8557, -1.5919, 0.35538, -2.0502, 0.10524, -1.5976, 0.0, -1.8614, -1.6008, -0.34892, -1.9818, 0.10153, -1.5829, 0.0,
                    0.26, -1.6008, 0.3489, -1.9818, 0.0, -1.5829, 0.0, -0.26, -1.6008, -0.3489, -1.9818, -0.0, -1.5829, 0.0,
                    0.36, -1.83, 0.47, -2.35, 0.0, -1.2, 0.0, -0.36, -1.83, -0.47, -2.35, -0.0, -1.2, 0.0]
        meta:
          name: Home teleop arms
          usage: demo
          description: Go home with the two teleop arms

      offer_teleop_arms:
        joints: [arm_teleop_left_1_joint, arm_teleop_left_2_joint, arm_teleop_left_3_joint, arm_teleop_left_4_joint, arm_teleop_left_5_joint, arm_teleop_left_6_joint, arm_teleop_left_7_joint, arm_teleop_right_1_joint, arm_teleop_right_2_joint, arm_teleop_right_3_joint, arm_teleop_right_4_joint, arm_teleop_right_5_joint, arm_teleop_right_6_joint, arm_teleop_right_7_joint]
        times_from_start: [0.0]
        positions: [-0.25843, -0.57522, 0.50314, -2.0337, 0.0, 1.0543, 1.5708, 0.25843, -0.57522, -0.50314, -2.0337, 0.0, 1.0543, -1.5708]
        meta:
          name: offer teleop arms
          usage: demo
          description: offer with the two teleop arms

      offer_teleop_left:
        joints: [arm_teleop_left_1_joint, arm_teleop_left_2_joint, arm_teleop_left_3_joint, arm_teleop_left_4_joint, arm_teleop_left_5_joint, arm_teleop_left_6_joint, arm_teleop_left_7_joint]
        times_from_start: [0.0]
        positions: [-0.25843, -0.57522, 0.50314, -2.0337, 0.0, 1.0543, 1.5708]
        meta:
          name: offer_left
          usage: demo
          description: offer_left   

      offer_teleop_right:
        joints: [arm_teleop_right_1_joint, arm_teleop_right_2_joint, arm_teleop_right_3_joint, arm_teleop_right_4_joint, arm_teleop_right_5_joint, arm_teleop_right_6_joint, arm_teleop_right_7_joint]
        times_from_start: [0.0]
        positions: [0.25843, -0.57522, -0.50314, -2.0337, 0.0, 1.0543, -1.5708]
        meta:
          name: offer_right teleop arm
          usage: demo
          description: offer_right teleop arm

      starting_teleop_master_arms:
        joints: [arm_teleop_left_1_joint, arm_teleop_left_2_joint, arm_teleop_left_3_joint, arm_teleop_left_4_joint, arm_teleop_left_5_joint, arm_teleop_left_6_joint, arm_teleop_left_7_joint, arm_teleop_right_1_joint, arm_teleop_right_2_joint, arm_teleop_right_3_joint, arm_teleop_right_4_joint, arm_teleop_right_5_joint, arm_teleop_right_6_joint, arm_teleop_right_7_joint]
        times_from_start: [0.0, 5.0]
        positions: [1.8557, -1.5919, 0.35538, -2.2, 0.10524, -1.5976, 0.0, -1.8614, -1.6008, -0.34892, -1.9818, 0.10153, -1.5829, 0.0,
                    2.8, -1.81, -0.56, -2.20, -2.6, 0.91, -0.26, -2.8, -1.81, 0.56, -2.20, 2.6, 0.91, -0.26]
        meta:
          name: Starting pose for master arm
          usage: demo
          description: Starting pose for master arm

      starting_teleop_slave_arms:
        joints: [torso_lift_joint, arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_left_6_joint, arm_left_7_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint, arm_right_6_joint, arm_right_7_joint]
        times_from_start: [0.0, 5.0]
        positions: [0.14, 1.8557, -1.5919, 0.35538, -2.2, 0.10524, -1.5976, 0.0, -1.8614, -1.6008, -0.34892, -1.9818, 0.10153, -1.5829, 0.0,
                    0.27, 2.8, -1.81, -0.56, -2.20, -2.6, 0.91, -0.26, -2.8, -1.81, 0.56, -2.20, 2.6, 0.91, -0.26]
        meta:
          name: Starting pose for slave arm
          usage: demo
          description: Starting pose for slave arm

      close_teleop_left:
        joints: [gripper_teleop_left_finger_joint]
        positions: [0.80]
        times_from_start: [0.5]
        meta:
          name: Close Left Gripper
          usage: demo
          description: 'Closes left gripper'
      
      close_teleop_left_half:
        joints: [gripper_teleop_left_finger_joint]
        positions: [0.40]
        times_from_start: [0.5]
        meta:
          name: Close Left Gripper Half
          usage: demo
          description: 'Closes left gripper halfway'

      open_teleop_left:
        joints: [gripper_teleop_left_finger_joint]
        positions: [0.0]
        times_from_start: [0.5]
        meta:
          name: Open Left Gripper
          usage: demo
          description: 'Open left gripper'
      
      close_teleop_right:
        joints: [gripper_teleop_right_finger_joint]
        positions: [0.80]
        times_from_start: [0.5]
        meta:
          name: Close Right Gripper
          usage: demo
          description: 'Closes right gripper'
      
      close_teleop_right_half:
        joints: [gripper_teleop_right_finger_joint]
        positions: [0.40]
        times_from_start: [0.5]
        meta:
          name: Close Right Gripper Half
          usage: demo
          description: 'Closes right gripper halfway'

      open_teleop_right:
        joints: [gripper_teleop_right_finger_joint]
        positions: [0.0]
        times_from_start: [0.5]
        meta:
          name: Open Right Gripper
          usage: demo
          description: 'Open right gripper'

